### ISSUE TITLE
Attack failed

### ISSUE THREAD

**Issue by FayeWong98** [PentesterES/Delorean#9]
I use this tool to deceive the victim machine, the process is as follows:

1.sudo iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 10000
sudo iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 123 -j REDIRECT --to-port 123

2.sudo arpspoof -i wlan0 -t 192.168.0.131 192.168.0.1

3. Open another terminal window during arpspoof attack, then 
    sudo python delorean.py

The result is as follows:

1. Ubuntu 20.04 laptop can be successfully spoofed

2. In addition, I have a hardware machine that can obtain ntp time. I can obtain the time by entering pool.ntp.org; however, the delorean attack on the machine failed. I am very confused about this. Maybe the machine has some protection on ntp? I want to ask for help here.

**Comment by jselvi** [comment]
Can you show me Delorean's output?
It should be something like this, if it's receiving connections:
```bash
[19:44:42] Sent to 192.168.10.113:123 - Going to the future! 2018-08-31 19:44 
[19:45:18] Sent to 192.168.10.113:123 - Going to the future! 2018-08-31 19:45
```

**Comment by FayeWong98** [comment]
Time spoofing is achieved when spoofing Thinkpad laptop time;

But when spoofing our lab machine, the machine time stays the same and always gets the real time;
delorean.py output is empty!

I was able to make sure that my host computer and the machine are on the same LAN (my ip-192.168.1.101, machine ip-192.168.1.100)

**Comment by jselvi** [comment]
@FayeWong98 I regret to say that, if you don't share more detailed information (including Delorian output), I won't be able to help.

**Comment by FayeWong98** [comment]
What I mean is: after delorean.py is executed, there is no output in the console.

**Comment by jselvi** [comment]
Ok, that means you are not correctly intercepting NTP traffic, or maybe your target computer is not generating NTP requests when you expect. I would try to confirm that interception is working by using ntpdate in your target machine to see if it is intercepted by Delorean.

If that works, it means your target is not trying to sync its clock. This talk is from 2015, so I'm not sure if what I said is still true in 2023, but please have a look: [DEFCON](https://youtu.be/hkw9tFnJk8k?t=1146). If your target is a virtual machine, it may happen that you have activated time synchronisation with your host, so it won't send NTP packets as it is sync by vm tools.

Hope this helps.

**Comment by FayeWong98** [comment]
I operated using the following command:

1. sudo iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 10000
sudo iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 123 -j REDIRECT --to-port 123

2. sudo arpspoof -i wlan0 -t 192.168.1.100 192.168.1.1

3. (Open another terminal window during arpspoof attack, then)
sudo python delorean.py

Is there something wrong with the command I entered?

**Comment by jselvi** [comment]
The way to verify if there's something wrong or not is in my previous message.

I'm closing this thread. If you follow my instructions and you still think it's a Delorean problem, feel free to reopen it, but please do not reopen it to ask about basic MitM concepts, as those are not Delorean specific. I'm sure there are other forums or chats where generic MitM questions fit better.
